# NiceChat v1.0
# Supports Placeholder API, Vault, HEX Color
# Formatting is using the ampersand character (&)
# WARNING! To plugin work correctly, do this:
# - Placeholder API and LuckPerms are must be installed
# - Don't use this plugin with other plugins for chat formatting
# by PansanGG_, from Russia

default-message: "{PLAYER} &r>> &7{MESSAGE}"
unique-messages:
  # {PLAYER} = LuckPerms prefix, nickname, and LuckPerms suffix; {MESSAGE} = message sent by player.
  # These GROUPS ARE EXAMPLES! You need to add your groups.
  enabled: true
  default: "{PLAYER} &r>> &7{MESSAGE}"
  vip: "{PLAYER} &r>> &#ebb609{MESSAGE}"
  admin: "👑 {PLAYER} &r>> &c{MESSAGE}"
messages:
  missing-permissions: "You don't have permission!"
profanity-filter: # Filters profanity in messages (SUPPORTS ONLY RUSSIAN LANGUAGE!)
  enabled: true
  replacing-char: "#" # Character with which profanity will be replaced
  bypass-players: # List of players who can swear
    - Nickname
    - Nickname2
  regex: "(?<![а-яё])(?:(?:(?:у|[нз]а|(?:хитро|не)?вз?[ыьъ]|с[ьъ]|(?:и|ра)[зс]ъ?|(?:о[тб]|п[оа]д)[ьъ]?|(?:\S(?=[а-яё]))+?[оаеи-])-?)?(?:[её](?:б(?!о[рй]|рач)|п[уа](?:ц|тс))|и[пб][ае][тцд][ьъ]).*?|(?:(?:н[иеа]|ра[зс]|[зд]?[ао](?:т|дн[оа])?|с(?:м[еи])?|а[пб]ч)-?)?ху(?:[яйиеёю]|л+и(?!ган)).*?|бл(?:[эя]|еа?)(?:[дт][ьъ]?)?|\S*?(?:п(?:[иеё]зд|ид[аое]?р|ед(?:р(?!о)|[аое]р|ик)|охую)|бля(?:[дбц]|тс)|[ое]ху[яйиеё]|хуйн).*?|(?:о[тб]?|про|на|вы)?м(?:анд(?:[ауеыи](?:л(?:и[сзщ])?[ауеиы])?|ой|[ао]в.*?|юк(?:ов|[ауи])?|е[нт]ь|ища)|уд(?:[яаиое].+?|е?н(?:[ьюия]|ей))|[ао]л[ао]ф[ьъ](?:[яиюе]|[еёо]й))|елд[ауые].*?|ля[тд]ь|(?:[нз]а|по)х)(?![а-яё])"
  punishment: # Do something when some player swears too much
    enabled: false
    max-count: 5 # Max count of profanity words in a message
    cmd: "kick {PLAYER} Don't swear!" # Command that will be issued when max-count is exceeded. {PLAYER} = nickname of a player who swears too much

# Thanks to:
# - Camp3r_RU ♥
# - MeexReay ♥