# NiceChat v1.0 (by PansanGG_)
#     Supports PlaceholderAPI, Luckperms and HEX Colors
#     Formatting is using the ampersand character (&)
#     WARNING! This plugin requires ProtocolLib


# Permissions
#     nicechat.command.nicechat - Access to use /nicechat command
#     nicechat.command.reload   - Access to use /nicechat reload command
#     nicechat.chat.color       - Access to use chat colors in messages
#     nicechat.chat.delete      - Access to delete your own messages
#     nicechat.chat.edit        - Access to edit your own messages
#     nicechat.chat.delete_all  - Access to delete all messages
#     nicechat.chat.edit_all    - Access to edit all messages


# Default message format
#     It is used in all messages not modified via unique-messages
#     {PLAYER} is changed to the name of the message author and {MESSAGE} is changed to the text of the message
#     All placeholders from PlaceholderAPI also work

default-message: "{DELETE}{EDIT}{PLAYER} &r>> &7{MESSAGE}"


# Unique messages
#     Unique message formats for each benefit
#     {PLAYER} also contains the privilege prefix and suffix
#     This feature also requires LuckPerms

unique-messages:
  enabled: true                          # Is this feature enabled?
  default: "{DELETE}{EDIT}{PLAYER} &r>> &7{MESSAGE}"   # This is just example groups
  vip: "{DELETE}{EDIT}{PLAYER} &r>> &#ebb609{MESSAGE}"
  admin: "{DELETE}{EDIT}{PLAYER} &r>> &c{MESSAGE}"


# Action buttons
#     Adds delete and edit buttons to messages
#     You need to write {DELETE} and {EDIT} in formats where you need this buttons

action-buttons:
  enabled: true                  # Do you really need this buttons?
  delete-button: "&c[&4🗑&c]&r "  # Delete button
  edit-button: "&e[&6📝&e]&r "    # Edit button
  delete-button-hidden: "    "   # Delete button when player isn't accessed to delete message
  edit-button-hidden: "    "     # Edit button when player isn't accessed to edit message
  messages-cache: 500            # Message buffer size

# Profanity filter
#     Swear filter, replaces swear words with any symbol (default #)
#     There is a penalty for using swear words above a certain threshold
#     Defines obscene words through regexes located in regex.txt

profanity-filter:
  enabled: true           # Do I need to filter profanity in messages?
  replacing-char: "#"     # Symbol with which profanity will be replaced (fuck -> ####)
  bypass-players:         # List of players who can bypass this filter
    - Nickname
    - Nickname2


  # Punishment
  #     Execute command when some player swears too much
  #     Only one type of punishment, will be corrected in the future

  punishment:
    enabled: false                    # Do I need to punish players for swear?
    max-count: 5                      # Max count of profanity words in a message
    cmd: "kick {PLAYER} Don't swear!" # Command that will be issued when max-count is exceeded.


# Messages
#     The text of all messages and plugin hints that players can see

messages:
  delete-hint: "Delete this message"
  edit-hint: "Edit this message"
  delete-finished: "Message deleted!"
  edit-finished: "Message edited!"
  reload: "Reloading..."
  reload-finished: "Reload finished"
