name: NiceChat
version: '${project.version}'
main: pansangg.nicechat.Main
api-version: '1.18'
depend: [ ProtocolLib ]

commands:
  nicechat:
    description: "Main NiceChat command"
    permission: nicechat.command.nicechat

permissions:
  nicechat.command.nicechat:
    default: true
  nicechat.command.reload:
    default: op
  nicechat.chat.color:
    default: op
  nicechat.chat.delete:
    default: true
  nicechat.chat.edit:
    default: true
  nicechat.chat.delete_all:
    default: op
  nicechat.chat.edit_all:
    default: op