name: NiceChat
version: '${project.version}'
main: pansangg.nicechat.Main
api-version: '1.18'

commands:
  nicechat:
    description: "Main NiceChat command"
    permission: nicechat.command.reload

permissions:
  nicechat.command.reload:
    default: op